INSERT INTO country (id, code, name) VALUES (1, 'BRA', 'Brasil');
INSERT INTO city (id, country_id, name) VALUES (1, 1, 'Recife');
INSERT INTO stadium (id, city_id, name, capacity) VALUES (1, 1, 'Estadio das Pontes', 18000);
INSERT INTO club (id, city_id, stadium_id, name, short_name) VALUES (1, 1, 1, 'Recife Azul', 'RAZ');
INSERT INTO club (id, city_id, stadium_id, name, short_name) VALUES (2, 1, 1, 'Recife Vermelho', 'RVM');
INSERT INTO competition (id, country_id, name, competition_type) VALUES (1, 1, 'Amistoso da Fundacao', 'friendly');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (1, 1, 1, 'Caio', 'Alencar', '2000-01-01', 1, 'GK');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (2, 1, 1, 'Davi', 'Barros', '2001-02-02', 2, 'RB');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (3, 1, 1, 'Enzo', 'Cavalcanti', '2002-03-03', 3, 'CB');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (4, 1, 1, 'Felipe', 'Dantas', '2003-04-04', 4, 'CB');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (5, 1, 1, 'Gabriel', 'Esteves', '2004-05-05', 5, 'LB');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (6, 1, 1, 'Heitor', 'Freire', '2005-06-06', 6, 'DM');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (7, 1, 1, 'Igor', 'Gouveia', '2000-07-07', 7, 'CM');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (8, 1, 1, 'Joao', 'Holanda', '2001-08-08', 8, 'AM');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (9, 1, 1, 'Lucas', 'Lins', '2002-09-09', 9, 'RW');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (10, 1, 1, 'Mateus', 'Medeiros', '2003-01-10', 10, 'ST');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (11, 1, 1, 'Nicolas', 'Nogueira', '2004-02-11', 11, 'LW');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (12, 1, 1, 'Otavio', 'Paes', '2005-03-12', 12, 'GK');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (13, 1, 1, 'Rafael', 'Queiroz', '2000-04-13', 13, 'CB');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (14, 1, 1, 'Samuel', 'Ramos', '2001-05-14', 14, 'CM');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (15, 1, 1, 'Victor', 'Siqueira', '2002-06-15', 15, 'ST');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (16, 1, 2, 'Andre', 'Amaral', '2002-04-08', 1, 'GK');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (17, 1, 2, 'Bruno', 'Bezerra', '2003-05-09', 2, 'RB');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (18, 1, 2, 'Cesar', 'Campos', '2004-06-10', 3, 'CB');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (19, 1, 2, 'Diego', 'Duarte', '2005-07-11', 4, 'CB');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (20, 1, 2, 'Eduardo', 'Farias', '2000-08-12', 5, 'LB');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (21, 1, 2, 'Fabio', 'Gomes', '2001-09-13', 6, 'DM');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (22, 1, 2, 'Gustavo', 'Henriques', '2002-01-14', 7, 'CM');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (23, 1, 2, 'Henrique', 'Lacerda', '2003-02-15', 8, 'AM');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (24, 1, 2, 'Iago', 'Monteiro', '2004-03-16', 9, 'RW');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (25, 1, 2, 'Leandro', 'Nascimento', '2005-04-17', 10, 'ST');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (26, 1, 2, 'Marcos', 'Oliveira', '2000-05-18', 11, 'LW');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (27, 1, 2, 'Paulo', 'Pereira', '2001-06-19', 12, 'GK');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (28, 1, 2, 'Renato', 'Rocha', '2002-07-20', 13, 'CB');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (29, 1, 2, 'Thiago', 'Tavares', '2003-08-21', 14, 'CM');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code) VALUES (30, 1, 2, 'Wesley', 'Vieira', '2004-09-22', 15, 'ST');
