INSERT INTO country (id, code, name) VALUES (1, 'BRA', 'Brasil');
INSERT INTO city (id, country_id, name) VALUES (1, 1, 'Recife');
INSERT INTO stadium (id, city_id, name, capacity) VALUES (1, 1, 'Estadio das Pontes', 18000);
INSERT INTO club (id, city_id, stadium_id, name, short_name) VALUES (1, 1, 1, 'Recife Azul', 'RAZ');
INSERT INTO club (id, city_id, stadium_id, name, short_name) VALUES (2, 1, 1, 'Recife Vermelho', 'RVM');
INSERT INTO competition (id, country_id, name, competition_type) VALUES (1, 1, 'Amistoso da Fundacao', 'friendly');
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (1, 1, 1, 'Caio', 'Alencar', '2000-01-01', 1, 'GK', 8, 9, 14, 8, 5, 4, 3, 15, 15);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (2, 1, 1, 'Davi', 'Barros', '2001-02-02', 2, 'RB', 17, 15, 9, 13, 6, 15, 12, 10, 3);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (3, 1, 1, 'Enzo', 'Cavalcanti', '2002-03-03', 3, 'CB', 9, 15, 16, 8, 6, 15, 9, 15, 1);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (4, 1, 1, 'Felipe', 'Dantas', '2003-04-04', 4, 'CB', 11, 12, 18, 10, 3, 17, 6, 17, 2);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (5, 1, 1, 'Gabriel', 'Esteves', '2004-05-05', 5, 'LB', 13, 16, 10, 14, 7, 11, 13, 11, 4);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (6, 1, 1, 'Heitor', 'Freire', '2005-06-06', 6, 'DM', 10, 14, 15, 13, 9, 15, 8, 16, 1);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (7, 1, 1, 'Igor', 'Gouveia', '2000-07-07', 7, 'CM', 14, 16, 10, 16, 9, 14, 13, 12, 3);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (8, 1, 1, 'Joao', 'Holanda', '2001-08-08', 8, 'AM', 12, 15, 10, 13, 14, 6, 17, 13, 1);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (9, 1, 1, 'Lucas', 'Lins', '2002-09-09', 9, 'RW', 18, 13, 11, 12, 10, 7, 15, 13, 2);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (10, 1, 1, 'Mateus', 'Medeiros', '2003-01-10', 10, 'ST', 13, 14, 13, 13, 17, 3, 14, 12, 4);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (11, 1, 1, 'Nicolas', 'Nogueira', '2004-02-11', 11, 'LW', 17, 12, 10, 11, 14, 6, 14, 12, 1);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (12, 1, 1, 'Otavio', 'Paes', '2005-03-12', 12, 'GK', 10, 11, 11, 10, 2, 6, 5, 12, 17);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (13, 1, 1, 'Rafael', 'Queiroz', '2000-04-13', 13, 'CB', 9, 15, 16, 8, 6, 15, 9, 15, 1);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (14, 1, 1, 'Samuel', 'Ramos', '2001-05-14', 14, 'CM', 13, 15, 14, 15, 8, 13, 12, 16, 2);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (15, 1, 1, 'Victor', 'Siqueira', '2002-06-15', 15, 'ST', 13, 14, 13, 13, 17, 3, 14, 12, 4);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (16, 1, 2, 'Andre', 'Amaral', '2002-04-08', 1, 'GK', 8, 9, 14, 8, 5, 4, 3, 15, 15);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (17, 1, 2, 'Bruno', 'Bezerra', '2003-05-09', 2, 'RB', 17, 15, 9, 13, 6, 15, 12, 10, 3);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (18, 1, 2, 'Cesar', 'Campos', '2004-06-10', 3, 'CB', 9, 15, 16, 8, 6, 15, 9, 15, 1);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (19, 1, 2, 'Diego', 'Duarte', '2005-07-11', 4, 'CB', 11, 12, 18, 10, 3, 17, 6, 17, 2);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (20, 1, 2, 'Eduardo', 'Farias', '2000-08-12', 5, 'LB', 13, 16, 10, 14, 7, 11, 13, 11, 4);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (21, 1, 2, 'Fabio', 'Gomes', '2001-09-13', 6, 'DM', 10, 14, 15, 13, 9, 15, 8, 16, 1);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (22, 1, 2, 'Gustavo', 'Henriques', '2002-01-14', 7, 'CM', 14, 16, 10, 16, 9, 14, 13, 12, 3);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (23, 1, 2, 'Henrique', 'Lacerda', '2003-02-15', 8, 'AM', 12, 15, 10, 13, 14, 6, 17, 13, 1);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (24, 1, 2, 'Iago', 'Monteiro', '2004-03-16', 9, 'RW', 18, 13, 11, 12, 10, 7, 15, 13, 2);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (25, 1, 2, 'Leandro', 'Nascimento', '2005-04-17', 10, 'ST', 13, 14, 13, 13, 17, 3, 14, 12, 4);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (26, 1, 2, 'Marcos', 'Oliveira', '2000-05-18', 11, 'LW', 17, 12, 10, 11, 14, 6, 14, 12, 1);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (27, 1, 2, 'Paulo', 'Pereira', '2001-06-19', 12, 'GK', 10, 11, 11, 10, 2, 6, 5, 12, 17);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (28, 1, 2, 'Renato', 'Rocha', '2002-07-20', 13, 'CB', 9, 15, 16, 8, 6, 15, 9, 15, 1);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (29, 1, 2, 'Thiago', 'Tavares', '2003-08-21', 14, 'CM', 13, 15, 14, 15, 8, 13, 12, 16, 2);
INSERT INTO player (id, nationality_country_id, club_id, first_name, last_name, birth_date, squad_number, position_code, pace, stamina, strength, passing, shooting, tackling, dribbling, positioning, goalkeeping) VALUES (30, 1, 2, 'Wesley', 'Vieira', '2004-09-22', 15, 'ST', 13, 14, 13, 13, 17, 3, 14, 12, 4);

-- TACT-00: the two Recife clubs deliberately set up differently, so a match between them shows
-- the tactical model doing something rather than two identical shapes cancelling out.
INSERT INTO club_tactics (club_id, formation, defensive_line_height, pressing_intensity, directness) VALUES (1, '4-3-3', 15, 16, 13);
INSERT INTO club_tactics (club_id, formation, defensive_line_height, pressing_intensity, directness) VALUES (2, '5-3-2', 6, 7, 8);

-- COMP-00: the two Recife clubs contest a league, and a new career starts on its first
-- matchday. A double round-robin between two clubs is two matchdays, one at each ground —
-- small, but a real season with a real table rather than a placeholder.
INSERT INTO competition (id, country_id, name, competition_type) VALUES (2, 1, 'Campeonato Pernambucano', 'league');
INSERT INTO season (id, competition_id, start_date, current_matchday) VALUES (1, 2, '2026-02-07', 0);
INSERT INTO season_club (season_id, club_id) VALUES (1, 1);
INSERT INTO season_club (season_id, club_id) VALUES (1, 2);
