<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SoccerSim.Infrastructure</RootNamespace>
    <AssemblyName>SoccerSim.Infrastructure</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SoccerSim.Core/SoccerSim.Core.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
</Project>
